Fix

diff --git a/bin/download b/bin/download
--- a/bin/download
+++ b/bin/download
@@ -1,20 +1,22 @@
 #!/usr/bin/env bash
-set -eu
-[ "${BASH_VERSINFO[0]}" -ge 3 ] && set -o pipefail
+set -euo pipefail
 
-PLUGIN_DIR="$(dirname "${BASH_SOURCE[0]}")/.."
+current_script_path=${BASH_SOURCE[0]}
+plugin_dir=$(dirname "$(dirname "$current_script_path")")
 
-download_ruby () {
-    local version=$1
-    local download_path=$2
-    local platform=""
-    local arch=""
+# shellcheck source=../lib/utils.sh
+source "${plugin_dir}/lib/utils.sh"
 
-    # TODO: Platform and Architecture
-    # platform=$(get_platform)
-    # arch=$(get_arch)
-    download_url="https://github.com/ruby/ruby-builder/releases/download/toolcache/ruby-${version}-ubuntu-22.04.tar.gz"
-    curl "$download_url" -o "${download_path}/archive.tar.gz"
-}
+mkdir -p "$ASDF_DOWNLOAD_PATH"
+echo "download_path: $ASDF_DOWNLOAD_PATH"
+release_file="$ASDF_DOWNLOAD_PATH/ruby-$ASDF_INSTALL_VERSION.tar.gz"
 
-download_ruby "$ASDF_INSTALL_VERSION" "$ASDF_DOWNLOAD_PATH"
+# Download tar.gz file to the download directory
+download_prebuilt_release "$ASDF_INSTALL_VERSION" "$release_file"
+
+# Extract contents of tar.gz file into the download directory
+tar -xzf "$release_file" -C "$ASDF_DOWNLOAD_PATH" --strip-components=1 x64 || fail "Could not extract $release_file"
+echo "tar: $release_file"
+
+# Remove the tar.gz file since we don't need to keep it
+rm "$release_file"
